name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

      - name: Deploy Django app
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          ssh root@164.92.189.203 "cd /root/hello-nodejs && git pull origin main"
