name: Deploy to Web Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy web page
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          host: 164.92.189.203
          username: root
          script: |
            cd /root/hello-nodejs
            git pull origin master
