name: Deploy to Web Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy web page
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          SERVER_IP: 164.92.189.203
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          ssh-add - <<< "${DEPLOY_KEY}"
          ssh root@164.92.189.203 "cd /root/hello-nodejs && git pull origin master"
